import asyncio
from sqlalchemy import select, delete
from app.core.database import engine, Base, AsyncSessionLocal
from app.models.automotive import Brand, Car, Subsystem, Part, Fastener


async def seed_data():
    print("Re-initializing tables on Neon PostgreSQL...")
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)

    async with AsyncSessionLocal() as session:
        print("Clearing tables for deep architectural decomposition seed...")
        await session.execute(delete(Fastener))
        await session.execute(delete(Part))
        await session.execute(delete(Car))
        await session.execute(delete(Subsystem))
        await session.execute(delete(Brand))
        await session.commit()

        print("Seeding 5 Primary Knolling Assembly Tiers (Subsystems)...")
        categories_data = [
            {"name": "Aero Shell", "description": "Floating Outer Body Panels & Aero Shell (Hood, Splitters, Wings, Diffusers)"},
            {"name": "Monocoque", "description": "Bare Structural Unibody / Monocoque Frame, Safety Cell & Subframes"},
            {"name": "Powertrain", "description": "Engine Block, Transaxle, Differential, Turbochargers & Resonant Exhaust"},
            {"name": "Brakes & Gear", "description": "Wishbones, Multi-Piston Calipers, Carbon-Ceramic Rotors & Electronic Dampers"},
            {"name": "Hardware", "description": "Torque-to-Yield Fastener Grid, Aircraft Titanium Hardware & Fastener Arrays"},
        ]
        subsystem_map = {}
        for cat in categories_data:
            obj = Subsystem(**cat)
            session.add(obj)
            await session.flush()
            subsystem_map[obj.name] = obj

        print("Seeding Brands...")
        porsche = Brand(name="Porsche", country="Germany", logo_url="/logos/porsche.svg")
        mclaren = Brand(name="McLaren", country="United Kingdom", logo_url="/logos/mclaren.svg")
        ferrari = Brand(name="Ferrari", country="Italy", logo_url="/logos/ferrari.svg")
        nissan = Brand(name="Nissan", country="Japan", logo_url="/logos/nissan.svg")
        vw = Brand(name="Volkswagen", country="Germany", logo_url="/logos/vw.svg")
        bmw = Brand(name="BMW", country="Germany", logo_url="/logos/bmw.svg")
        session.add_all([porsche, mclaren, ferrari, nissan, vw, bmw])
        await session.flush()

        print("Seeding 5 Primary Motorsport Cars + BMW M4 CSL...")
        gt3_rs = Car(
            brand_id=porsche.id,
            model="911 GT3 RS",
            trim="Weissach Homologation Package (992.1)",
            year=2024,
            vin_prefix="WP0AF2A9",
            image_url="/assets/monocoque-exploded-v2.jpg",
        )
        mclaren_f1 = Car(
            brand_id=mclaren.id,
            model="F1 (XP5)",
            trim="Central Cockpit Le Mans Benchmark",
            year=1993,
            vin_prefix="SA9AB54B",
            image_url="/assets/mclaren-f1-cutaway.jpg",
        )
        ferrari_f40 = Car(
            brand_id=ferrari.id,
            model="F40",
            trim="Tipo F120A Homologation",
            year=1987,
            vin_prefix="ZFFGJ34B",
            image_url="/assets/ferrari-f40-cutaway.jpg",
        )
        skyline_r34 = Car(
            brand_id=nissan.id,
            model="Skyline GT-R (R34)",
            trim="V-Spec II Nürburgring Spec",
            year=1999,
            vin_prefix="BNR34-00",
            image_url="/assets/skyline-r34-cutaway.jpg",
        )
        golf_r = Car(
            brand_id=vw.id,
            model="Golf R",
            trim="Mk8 20 Years Edition",
            year=2024,
            vin_prefix="WVWZZZCD",
            image_url="/assets/vw-golfr-cutaway.jpg",
        )
        bmw_m4 = Car(
            brand_id=bmw.id,
            model="M4 CSL",
            trim="G82 Lightweight Homologation",
            year=2023,
            vin_prefix="WBS43AZ0",
            image_url="/assets/bmw-m4-knolling-teardown.jpg",
        )
        session.add_all([gt3_rs, mclaren_f1, ferrari_f40, skyline_r34, golf_r, bmw_m4])
        await session.flush()

        # Helper function to seed 12-component knolling dossiers
        async def seed_car_components(car, components):
            for item in components:
                part = Part(
                    car_id=car.id,
                    subsystem_id=subsystem_map[item["category"]].id,
                    part_number=item["part_number"],
                    name=item["name"],
                    category=item["category"],
                    sub_assembly=item.get("sub_assembly", item["category"]),
                    physical_layer=item.get("physical_layer", f"Tier: {item['category']}"),
                    material=item["material"],
                    surface_treatment=item.get("surface_treatment", "Automotive Spec"),
                    weight_kg=item["weight_kg"],
                    function=item["plainExplainer"],
                    manufacturing_process=item.get("manufacturing_process", "Precision CNC / Autoclave"),
                    joint_spec=item["joint_spec"],
                )
                session.add(part)
                await session.flush()

                # Add matching Fastener / Datum Pin
                fastener = Fastener(
                    part_id=part.id,
                    name=item["fastener_name"],
                    fastener_type=item.get("fastener_type", "Bolt"),
                    thread_size=item.get("thread_size", "M8x1.25"),
                    drive_type=item.get("drive_type", "Torx T30"),
                    grade=item.get("grade", "Grade 10.9"),
                    torque_spec_nm=item["torque_spec_nm"],
                    quantity_used=item.get("qty", 4),
                    x_percent=item["x_percent"],
                    y_percent=item["y_percent"],
                    notes=item["plainExplainer"],
                )
                session.add(fastener)
            await session.flush()

        # =====================================================================
        # 1. PORSCHE 911 GT3 RS (992.1) - 5 TIERS / 12 COMPONENTS
        # =====================================================================
        print("Seeding Porsche 911 GT3 RS knolling component dossiers...")
        porsche_dossier = [
            {
                "category": "Aero Shell",
                "name": "Dual-Element Active DRS Swan-Neck Wing",
                "plainExplainer": "Hydraulically tilts 34 degrees in 0.3 seconds to bleed drag on straights and clamp down with 860 kg of downforce in corners.",
                "part_number": "992-827-901-RS",
                "material": "High-Modulus Pre-Preg Carbon & 7075-T6 Pylons",
                "weight_kg": 7.2,
                "joint_spec": "M8x1.25 Grade 10.9 (42 Nm into Shock Towers)",
                "fastener_name": "Swan-Neck Pylon Billet Chassis Mount Bolt",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 13mm", "grade": "10.9", "torque_spec_nm": 42.0,
                "x_percent": 74.0, "y_percent": 16.0, "qty": 6,
            },
            {
                "category": "Aero Shell",
                "name": "Carbon Fiber Hood with S-Duct Extractors",
                "plainExplainer": "Evacuates blistering heat from the central motorsport radiator and routes downforce-generating air over the roof.",
                "part_number": "992-823-010-CF",
                "material": "Autoclaved Pre-Preg Carbon Fiber",
                "weight_kg": 3.8,
                "joint_spec": "M6 Torx T25 (12 Nm)",
                "fastener_name": "S-Duct Hood Carbon Quick-Latch Pin",
                "fastener_type": "Pin", "thread_size": "M6x1.0", "drive_type": "Torx T25", "grade": "8.8", "torque_spec_nm": 12.0,
                "x_percent": 26.0, "y_percent": 18.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "Aero Door Shells with Lateral Air-Channel Blades",
                "plainExplainer": "Carves wheel-well turbulence outward to feed clean, cool air directly into the rear flat-6 intake scoops.",
                "part_number": "992-831-010-RS",
                "material": "Carbon-Aramid Composite",
                "weight_kg": 6.9,
                "joint_spec": "M8 Door Hinge Fasteners (24 Nm)",
                "fastener_name": "CFRP Door Hinge High-Tensile Fastener",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Triple Square XZN M8", "grade": "10.9", "torque_spec_nm": 24.0,
                "x_percent": 86.0, "y_percent": 22.0, "qty": 4,
            },
            {
                "category": "Monocoque",
                "name": "AZ31B Hydroformed Magnesium Roof Panel",
                "plainExplainer": "Lowers the car's center of gravity by 7.5 millimeters at the highest structural point to eliminate lateral cornering roll.",
                "part_number": "992-817-010-MG",
                "material": "AZ31B-H24 Magnesium Alloy (1.1mm)",
                "weight_kg": 4.1,
                "joint_spec": "Dow Betamate 2090 + M5 Ti Bolts (6.2 Nm)",
                "fastener_name": "Magnesium Double-Bubble Structural Bonding Fastener",
                "fastener_type": "Bolt", "thread_size": "M5x0.8", "drive_type": "Torx T25", "grade": "Grade 5 Titanium", "torque_spec_nm": 6.2,
                "x_percent": 50.0, "y_percent": 38.0, "qty": 8,
            },
            {
                "category": "Monocoque",
                "name": "Carbon-Fiber Reinforced Unibody Safety Cell & FIA Half-Cage",
                "plainExplainer": "Delivers immense torsional rigidity so suspension geometry works with razor-sharp precision under 4.2G apex loading.",
                "part_number": "992-500-010-BIW",
                "material": "Al-Mg-Si Extrusions & CFRP Bracing with 25CrMo4 Steel",
                "weight_kg": 11.8,
                "joint_spec": "M10 Subframe Bolts (65 Nm)",
                "fastener_name": "Titanium Roll Cage Unibody Pad Anchor",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Hex 16mm", "grade": "10.9", "torque_spec_nm": 65.0,
                "x_percent": 68.0, "y_percent": 42.0, "qty": 6,
            },
            {
                "category": "Powertrain",
                "name": "4.0L Flat-6 NA Engine (MA1.77) with 6 ITBs",
                "plainExplainer": "Revving to 9,000 RPM, six dedicated intake butterflies eliminate hesitation for immediate throttle modulation mid-corner.",
                "part_number": "992-100-020-GT3",
                "material": "AlSi17Cu4Mg Cast Alusil Block & Titanium Rods",
                "weight_kg": 182.0,
                "joint_spec": "M10 Motor Mounts (85 Nm)",
                "fastener_name": "Rigid Valvetrain Finger-Follower Cam Bolt",
                "fastener_type": "Bolt", "thread_size": "M7x1.0", "drive_type": "Torx E10", "grade": "12.9", "torque_spec_nm": 16.0,
                "x_percent": 48.0, "y_percent": 58.0, "qty": 16,
            },
            {
                "category": "Powertrain",
                "name": "7-Speed Dual-Clutch PDK Transmission with Electronic LSD",
                "plainExplainer": "Swaps cogs in under 100 milliseconds and actively vectors locking torque across the rear wheels to stabilize trail-braking.",
                "part_number": "992-300-020-PDK",
                "material": "Die-Cast Aluminum & Case-Hardened Steel Gearsets",
                "weight_kg": 116.0,
                "joint_spec": "M10 Bellhousing Bolts (48 Nm)",
                "fastener_name": "PDK Transaxle Cross-Member Bolt",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Hex 16mm", "grade": "10.9", "torque_spec_nm": 48.0,
                "x_percent": 70.0, "y_percent": 60.0, "qty": 8,
            },
            {
                "category": "Powertrain",
                "name": "Inconel / Titanium Featherweight Racing Exhaust",
                "plainExplainer": "Crafted from thin-wall titanium to survive 850°C exhaust gas temperatures while cutting 9.5 kg off the rear overhang.",
                "part_number": "992-251-010-TI",
                "material": "Grade 2 Titanium & Inconel 625",
                "weight_kg": 9.8,
                "joint_spec": "M8 V-Band Clamps (18 Nm)",
                "fastener_name": "Titanium Center-Exit Muffler V-Band Clamp",
                "fastener_type": "Bolt", "thread_size": "M6x1.0", "drive_type": "Hex 10mm", "grade": "Inconel 718", "torque_spec_nm": 18.0,
                "x_percent": 30.0, "y_percent": 66.0, "qty": 2,
            },
            {
                "category": "Brakes & Gear",
                "name": "Monobloc 6-Piston Aluminum Brake Caliper",
                "plainExplainer": "Squeezes the carbon brake rotor with 6 pistons to stop the car safely under heavy track braking.",
                "part_number": "992-351-409-CC",
                "material": "Forged Monobloc Aluminum (Yellow Finish)",
                "weight_kg": 4.8,
                "joint_spec": "M14 Radial Bolts (140 Nm)",
                "fastener_name": "Teardrop Wishbone Lower Ball-Joint Spindle Stud",
                "fastener_type": "Bolt", "thread_size": "M14x1.5", "drive_type": "Hex 21mm", "grade": "12.9", "torque_spec_nm": 140.0,
                "x_percent": 12.0, "y_percent": 76.0, "qty": 2,
            },
            {
                "category": "Brakes & Gear",
                "name": "410mm Carbon-Silicon Carbide (PCCB) Brake Rotor",
                "plainExplainer": "Dissipates intense track heat without fade while saving 18.2 kg of unsprung spinning mass for faster suspension response.",
                "part_number": "992-351-410-CC",
                "material": "C/SiC Carbon Ceramic Matrix & Forged 7075-T6 Bell",
                "weight_kg": 6.8,
                "joint_spec": "M30x1.5 Motorsport Center-Lock Nut (600 Nm)",
                "fastener_name": "Motorsport Forged Center-Lock Wheel Nut",
                "fastener_type": "Nut", "thread_size": "M30x1.5 Special", "drive_type": "3/4-inch Center-Lock Drive", "grade": "Forged 7075-T6", "torque_spec_nm": 600.0,
                "x_percent": 16.0, "y_percent": 84.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "Teardrop Aero Double-Wishbones with PASM Coilovers",
                "plainExplainer": "Aerodynamically shaped suspension arms generate 40 kg of front downforce while completely resisting brake dive.",
                "part_number": "992-407-151-GT",
                "material": "Forged AlSi10Mg Aluminum & 42CrMo4 Spindle",
                "weight_kg": 5.6,
                "joint_spec": "M14x1.5 Ball-Joint Stud (140 Nm)",
                "fastener_name": "PASM Coilover Top Mount Flange Nut",
                "fastener_type": "Nut", "thread_size": "M12x1.25", "drive_type": "Hex 19mm", "grade": "10.9", "torque_spec_nm": 65.0,
                "x_percent": 32.0, "y_percent": 79.0, "qty": 6,
            },
            {
                "category": "Hardware",
                "name": "Torque-to-Yield Monocoque Fastener & Hardware Grid",
                "plainExplainer": "Mil-spec high-tensile hardware array ensuring structural integrity under extreme downforce and g-forces.",
                "part_number": "992-007-FAST-GRID",
                "material": "Grade 10.9 & 12.9 Dacromet Steel",
                "weight_kg": 3.2,
                "joint_spec": "M6–M14 Fasteners (10–140 Nm)",
                "fastener_name": "Subframe Yield Calibration Stud Grid",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Torx E14", "grade": "12.9", "torque_spec_nm": 85.0,
                "x_percent": 72.0, "y_percent": 92.0, "qty": 48,
            },
        ]
        await seed_car_components(gt3_rs, porsche_dossier)

        # =====================================================================
        # 2. MCLAREN F1 (XP5) - 5 TIERS / 12 COMPONENTS
        # =====================================================================
        print("Seeding McLaren F1 (XP5) knolling component dossiers...")
        mclaren_dossier = [
            {
                "category": "Aero Shell",
                "name": "Active Pop-Up Aerodynamic Airbrake Foil",
                "plainExplainer": "Raises 30 degrees during high-speed threshold braking to increase rear downforce and drag, stabilizing the rear axle.",
                "part_number": "XP5-827-AIRBRAKE",
                "material": "Carbon Fiber Composite",
                "weight_kg": 3.2,
                "joint_spec": "M8 Fasteners (32 Nm)",
                "fastener_name": "Airbrake Actuator Hinge Bolt",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 13mm", "grade": "Grade 5 Titanium", "torque_spec_nm": 32.0,
                "x_percent": 75.0, "y_percent": 16.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "Dihedral Butterfly Doors with Integral A-Pillars",
                "plainExplainer": "Swings upward and forward on patented single-pivot kinematic hinges to grant effortless access to the central cockpit.",
                "part_number": "XP5-831-DOOR",
                "material": "Toray T300 Carbon Pre-Preg & Nomex Honeycomb",
                "weight_kg": 5.4,
                "joint_spec": "Single-Pivot Kinematic Joint (28 Nm)",
                "fastener_name": "Dihedral Door Pivot Axis Pin",
                "fastener_type": "Pin", "thread_size": "M10x1.25", "drive_type": "Hex Socket", "grade": "Grade 5 Titanium", "torque_spec_nm": 28.0,
                "x_percent": 84.0, "y_percent": 22.0, "qty": 2,
            },
            {
                "category": "Aero Shell",
                "name": "Carbon-Composite Front Clamshell with Louvers",
                "plainExplainer": "Guides radiator exhaust and aerodynamic downforce across the windscreen while keeping frontal weight featherlight.",
                "part_number": "XP5-823-HOOD",
                "material": "Carbon Fiber & Kevlar Matrix",
                "weight_kg": 4.1,
                "joint_spec": "Aero Flush Latches (12 Nm)",
                "fastener_name": "Clamshell Flush Quick-Latch",
                "fastener_type": "Pin", "thread_size": "M6x1.0", "drive_type": "Aero Latch", "grade": "Titanium", "torque_spec_nm": 12.0,
                "x_percent": 26.0, "y_percent": 18.0, "qty": 4,
            },
            {
                "category": "Monocoque",
                "name": "Monolithic Carbon-Fiber Composite Monocoque Tub",
                "plainExplainer": "The world's first production carbon monocoque passenger cell, providing unyielding structural safety and torsional stiffness.",
                "part_number": "XP5-500-MONOCOQUE",
                "material": "High-Modulus Carbon Pre-Preg & Aluminum Honeycomb Core",
                "weight_kg": 100.0,
                "joint_spec": "Grade 5 Titanium Bulkhead Fasteners (75 Nm)",
                "fastener_name": "Monocoque Rear Bulkhead Structural Stud",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "Grade 5 Titanium", "torque_spec_nm": 75.0,
                "x_percent": 50.0, "y_percent": 40.0, "qty": 8,
            },
            {
                "category": "Monocoque",
                "name": "Central Cockpit Driving Cell & Molded Kevlar Seat",
                "plainExplainer": "Positions driver dead-center for optimal sightlines, zero parallax error, and perfect weight distribution.",
                "part_number": "XP5-501-SEAT",
                "material": "Kevlar-Reinforced Carbon Shell & Connolly Leather",
                "weight_kg": 6.8,
                "joint_spec": "Direct Chassis Threaded Inserts (45 Nm)",
                "fastener_name": "Central Seat Chassis Anchor Bolt",
                "fastener_type": "Bolt", "thread_size": "M10x1.25", "drive_type": "Hex 16mm", "grade": "10.9", "torque_spec_nm": 45.0,
                "x_percent": 67.0, "y_percent": 42.0, "qty": 4,
            },
            {
                "category": "Powertrain",
                "name": "6.1L 60° BMW Motorsport V12 Engine (S70/2)",
                "plainExplainer": "Produces 627 horsepower without turbos through 12 individual throttles and continuous variable valve timing.",
                "part_number": "XP5-S702-V12",
                "material": "Cast Aluminum Block & Titanium Connecting Rods",
                "weight_kg": 266.0,
                "joint_spec": "Engine Subframe Isolator Bolts (90 Nm)",
                "fastener_name": "V12 Subframe Cradle Mounting Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 19mm", "grade": "12.9", "torque_spec_nm": 90.0,
                "x_percent": 48.0, "y_percent": 58.0, "qty": 4,
            },
            {
                "category": "Powertrain",
                "name": "Transverse 6-Speed Manual Transaxle & Carbon Clutch",
                "plainExplainer": "Compact transverse packaging engineered by Gordon Murray to keep polar moment of inertia minimal for lightning turn-in.",
                "part_number": "XP5-TRANS-6SPD",
                "material": "Magnesium Alloy Casing & Billet Helical Gearsets",
                "weight_kg": 88.0,
                "joint_spec": "Magnesium Casing Fasteners (38 Nm)",
                "fastener_name": "Transaxle Magnesium Bellhousing Fastener",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Torx T45", "grade": "10.9", "torque_spec_nm": 38.0,
                "x_percent": 69.0, "y_percent": 58.0, "qty": 12,
            },
            {
                "category": "Powertrain",
                "name": "Hand-Welded Inconel Resonant Exhaust Manifold",
                "plainExplainer": "Equal-length equal-pulse exhaust runners crafted from paper-thin Inconel superalloy producing legendary V12 acoustic resonance.",
                "part_number": "XP5-EXH-INC",
                "material": "Inconel 625 Superalloy Sheet (0.8mm)",
                "weight_kg": 8.5,
                "joint_spec": "Inconel 718 Self-Locking Studs (22 Nm)",
                "fastener_name": "Inconel Exhaust Collector Nut",
                "fastener_type": "Nut", "thread_size": "M8x1.25", "drive_type": "Hex 12mm", "grade": "Inconel 718", "torque_spec_nm": 22.0,
                "x_percent": 31.0, "y_percent": 68.0, "qty": 24,
            },
            {
                "category": "Brakes & Gear",
                "name": "Brembo 4-Piston Monobloc Motorsport Caliper",
                "plainExplainer": "Direct pedal modulation caliper without ABS to provide pure, unfiltered hydraulic brake feedback directly to the driver's foot.",
                "part_number": "XP5-BREMBO-CAL",
                "material": "Monobloc Cast Aluminum Alloy",
                "weight_kg": 4.2,
                "joint_spec": "High-Tensile Caliper Carrier Bolts (110 Nm)",
                "fastener_name": "Front Upright Radial Caliper Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 17mm", "grade": "12.9", "torque_spec_nm": 110.0,
                "x_percent": 11.5, "y_percent": 75.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "332mm Ventilated High-Carbon Cast Steel Brake Rotor",
                "plainExplainer": "Specified by Gordon Murray for consistent pedal bite and immediate cold-weather response without the unpredictability of early carbon brakes.",
                "part_number": "XP5-BREMBO-ROT",
                "material": "High-Carbon Cast Iron Friction Disc & Billet Aluminum Bell",
                "weight_kg": 7.8,
                "joint_spec": "Forged Magnesium Wheel Lug Nuts (120 Nm)",
                "fastener_name": "Center-Lock Magnesium Drive Pin",
                "fastener_type": "Nut", "thread_size": "M14x1.5", "drive_type": "Hex 21mm", "grade": "Grade 5 Titanium", "torque_spec_nm": 120.0,
                "x_percent": 15.5, "y_percent": 83.0, "qty": 5,
            },
            {
                "category": "Brakes & Gear",
                "name": "Inboard Pushrod Horizontal Dampers with Eibach Springs",
                "plainExplainer": "Transfers wheel motions through cantilever rocker arms into inboard dampers, eliminating unsprung mass in the wheel arches.",
                "part_number": "XP5-BILSTEIN-DAM",
                "material": "Hard-Anodized Aluminum Monotube & Cr-Si Springs",
                "weight_kg": 4.8,
                "joint_spec": "Cantilever Rocker Pivot Bolts (52 Nm)",
                "fastener_name": "Inboard Rocker Arm Pivot Bolt",
                "fastener_type": "Bolt", "thread_size": "M10x1.25", "drive_type": "Hex 16mm", "grade": "Grade 5 Titanium", "torque_spec_nm": 52.0,
                "x_percent": 32.0, "y_percent": 78.0, "qty": 4,
            },
            {
                "category": "Hardware",
                "name": "Mil-Spec Grade 5 Titanium Aerospace Fastener Grid",
                "plainExplainer": "Each fastener was individually weighed during development to guarantee Gordon Murray's stringent 1,138 kg total curb weight target.",
                "part_number": "XP5-AERO-FAST",
                "material": "Ti-6Al-4V Aerospace Grade 5 Titanium",
                "weight_kg": 2.8,
                "joint_spec": "M5–M14 Fasteners (8–120 Nm)",
                "fastener_name": "Hollow-Head Aerospace Titanium Bolt",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Torx T30", "grade": "Grade 5 Titanium", "torque_spec_nm": 28.0,
                "x_percent": 73.0, "y_percent": 92.0, "qty": 60,
            },
        ]
        await seed_car_components(mclaren_f1, mclaren_dossier)

        # =====================================================================
        # 3. FERRARI F40 (TIPO F120A) - 5 TIERS / 12 COMPONENTS
        # =====================================================================
        print("Seeding Ferrari F40 knolling component dossiers...")
        ferrari_dossier = [
            {
                "category": "Aero Shell",
                "name": "Fixed Composite Rear Aerofoil with Integrated Gurney Flap",
                "plainExplainer": "Provides essential high-speed aerodynamic downforce at the F40's 324 km/h (201 mph) top speed.",
                "part_number": "120A-827-WING",
                "material": "Kevlar & Carbon Fiber Composite",
                "weight_kg": 5.6,
                "joint_spec": "Structural Composite Fasteners (35 Nm)",
                "fastener_name": "Rear Wing Pylon Chassis Stud",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 13mm", "grade": "10.9", "torque_spec_nm": 35.0,
                "x_percent": 73.0, "y_percent": 16.0, "qty": 6,
            },
            {
                "category": "Aero Shell",
                "name": "Front Clamshell Bonnet with NACA Cooling Ducts",
                "plainExplainer": "Single-piece clamshell incorporating NACA flush ducts to ingest cooling air into oil coolers without aerodynamic drag.",
                "part_number": "120A-823-HOOD",
                "material": "Kevlar-Reinforced Carbon Fiber",
                "weight_kg": 8.2,
                "joint_spec": "Hinge Pivot Pins (18 Nm)",
                "fastener_name": "Clamshell Bonnet Hinge Pin",
                "fastener_type": "Pin", "thread_size": "M8x1.25", "drive_type": "Hex 14mm", "grade": "8.8", "torque_spec_nm": 18.0,
                "x_percent": 26.0, "y_percent": 18.0, "qty": 2,
            },
            {
                "category": "Aero Shell",
                "name": "Full Kevlar-Nomex Clamshell Rear Engine Cover",
                "plainExplainer": "Houses transparent louvered Lexan screen to evacuate blistering turbocharger heat straight into the rear slipstream.",
                "part_number": "120A-831-DECK",
                "material": "Kevlar-Nomex Honeycomb Composite",
                "weight_kg": 11.5,
                "joint_spec": "Rear Clamshell Rotary Latches (24 Nm)",
                "fastener_name": "Rear Engine Cover Safety Latch Pin",
                "fastener_type": "Pin", "thread_size": "M8x1.25", "drive_type": "Aero Latch", "grade": "10.9", "torque_spec_nm": 24.0,
                "x_percent": 86.0, "y_percent": 22.0, "qty": 4,
            },
            {
                "category": "Monocoque",
                "name": "Tubular Steel Spaceframe with Bonded Kevlar Bulkheads",
                "plainExplainer": "Chrome-moly steel spaceframe reinforced with structural composite panels delivering pure Group B motorsport rigidity.",
                "part_number": "120A-500-CHASSIS",
                "material": "25CrMo4 Tubular Steel & Bonded Kevlar Bulkheads",
                "weight_kg": 115.0,
                "joint_spec": "Spaceframe Joining Hardware (80 Nm)",
                "fastener_name": "Tubular Spaceframe Bulkhead Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 19mm", "grade": "12.9", "torque_spec_nm": 80.0,
                "x_percent": 50.0, "y_percent": 40.0, "qty": 12,
            },
            {
                "category": "Monocoque",
                "name": "Lightweight Composite Door with Cable Pull Latch",
                "plainExplainer": "Featherlight composite door shell weighing just 1.5 kg, featuring sliding Lexan plastic windows and green pull strings.",
                "part_number": "120A-831-DOOR",
                "material": "Raw Carbon-Kevlar Composite (Unpainted Inner)",
                "weight_kg": 1.5,
                "joint_spec": "Hinge Pivot Pins (26 Nm)",
                "fastener_name": "Composite Door Hinge Hanger",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 13mm", "grade": "10.9", "torque_spec_nm": 26.0,
                "x_percent": 68.0, "y_percent": 42.0, "qty": 4,
            },
            {
                "category": "Powertrain",
                "name": "2.9L Twin-Turbocharged 90° V8 Engine (Tipo F120A)",
                "plainExplainer": "Twin IHI water-cooled turbochargers boost the lightweight 2.9-liter V8 to an explosive 478 horsepower.",
                "part_number": "120A-ENG-V8",
                "material": "Silumin Aluminum-Silicon Alloy Block & Nikasil Liners",
                "weight_kg": 168.0,
                "joint_spec": "V8 Engine Mounts (95 Nm)",
                "fastener_name": "Tipo F120A Motor Mount Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 19mm", "grade": "10.9", "torque_spec_nm": 95.0,
                "x_percent": 48.0, "y_percent": 58.0, "qty": 4,
            },
            {
                "category": "Powertrain",
                "name": "5-Speed Manual Dog-Leg Transaxle with ZF LSD",
                "plainExplainer": "Gated open-gate manual shifter connected directly to rear transaxle with straight-cut gears for race-grade torque capacity.",
                "part_number": "120A-TRANS-5SPD",
                "material": "Magnesium-Aluminum Casing & Hardened Steel Gears",
                "weight_kg": 78.0,
                "joint_spec": "Bellhousing Fasteners (52 Nm)",
                "fastener_name": "Dog-Leg Transaxle Bellhousing Stud",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Hex 17mm", "grade": "10.9", "torque_spec_nm": 52.0,
                "x_percent": 70.0, "y_percent": 60.0, "qty": 10,
            },
            {
                "category": "Powertrain",
                "name": "Triple Center-Exit Exhaust Silencer & Wastegate Pipe",
                "plainExplainer": "Central pipe vents raw wastegate exhaust gas while outer dual tips route silenced cylinder exhaust with legendary acoustic drama.",
                "part_number": "120A-EXH-TRIPLE",
                "material": "Stainless Steel & Ceramic Thermal Coating",
                "weight_kg": 14.5,
                "joint_spec": "Exhaust Manifold Studs (28 Nm)",
                "fastener_name": "Wastegate Bypass Pipe Clamp",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 13mm", "grade": "Stainless A4", "torque_spec_nm": 28.0,
                "x_percent": 30.0, "y_percent": 66.0, "qty": 6,
            },
            {
                "category": "Brakes & Gear",
                "name": "Brembo 4-Piston Aluminum Brake Calipers",
                "plainExplainer": "Direct non-assisted hydraulic calipers offering firm pedal resistance and complete unassisted modulation.",
                "part_number": "120A-BREMBO-CAL",
                "material": "Cast Aluminum Monobloc (Black Finish)",
                "weight_kg": 4.6,
                "joint_spec": "Caliper Carrier Bolts (120 Nm)",
                "fastener_name": "Front Caliper Mounting Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 19mm", "grade": "12.9", "torque_spec_nm": 120.0,
                "x_percent": 12.0, "y_percent": 76.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "330mm Drilled Cross-Ventilated Steel Brake Rotors",
                "plainExplainer": "Cross-drilled cooling holes disperse gas buildup between pad and rotor surface during high-speed deceleration.",
                "part_number": "120A-BREMBO-ROT",
                "material": "High-Carbon Steel Friction Ring & Aluminum Bell",
                "weight_kg": 8.1,
                "joint_spec": "Ronal Speedline Center-Lock Nut (550 Nm)",
                "fastener_name": "Center-Lock Octagonal Wheel Nut",
                "fastener_type": "Nut", "thread_size": "M28x1.5", "drive_type": "Octagonal 46mm", "grade": "Anodized Aluminum", "torque_spec_nm": 550.0,
                "x_percent": 16.0, "y_percent": 84.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "Double-Wishbone Suspension with Koni Adjustable Dampers",
                "plainExplainer": "Tubular steel wishbones provide unequal-length geometric camber control under high lateral cornering loads.",
                "part_number": "120A-KONI-DAMPER",
                "material": "Seamless Tubular Steel & Hydraulic Monotubes",
                "weight_kg": 7.2,
                "joint_spec": "Suspension Pivot Bushings (70 Nm)",
                "fastener_name": "Wishbone Eccentric Pivot Cam Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 19mm", "grade": "10.9", "torque_spec_nm": 70.0,
                "x_percent": 32.0, "y_percent": 79.0, "qty": 8,
            },
            {
                "category": "Hardware",
                "name": "Motorsport High-Tensile Cadmium-Plated Hardware Grid",
                "plainExplainer": "Cadmium-plated high-tensile hardware engineered to maintain clamping force through intense turbo heat cycles.",
                "part_number": "120A-FAST-GRID",
                "material": "Grade 10.9 Cadmium-Plated Steel",
                "weight_kg": 3.5,
                "joint_spec": "Various Fastener Specs (10–135 Nm)",
                "fastener_name": "Cadmium-Plated Spaceframe Fastener",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Hex 17mm", "grade": "10.9", "torque_spec_nm": 65.0,
                "x_percent": 73.0, "y_percent": 92.0, "qty": 52,
            },
        ]
        await seed_car_components(ferrari_f40, ferrari_dossier)

        # =====================================================================
        # 4. NISSAN SKYLINE GT-R (R34) - 5 TIERS / 12 COMPONENTS
        # =====================================================================
        print("Seeding Nissan Skyline GT-R (R34) knolling component dossiers...")
        nissan_dossier = [
            {
                "category": "Aero Shell",
                "name": "Adjustable Carbon Fiber Rear Spoiler with End Plates",
                "plainExplainer": "Features a four-position manual angle adjustment to balance rear downforce against top-speed drag on circuits.",
                "part_number": "NIS-R34-AERO-WING",
                "material": "2x2 Twill Carbon Fiber & Billet Uprights",
                "weight_kg": 4.5,
                "joint_spec": "M8 High-Tensile Bolts (28 Nm)",
                "fastener_name": "Carbon Wing Upright Mounting Bolt",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 12mm", "grade": "10.9", "torque_spec_nm": 28.0,
                "x_percent": 74.0, "y_percent": 16.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "Nismo Carbon Fiber Vented Hood with NACA Intake",
                "plainExplainer": "Draws ambient air directly to the twin turbochargers while extracting engine bay thermal heat through hood louvers.",
                "part_number": "NIS-R34-AERO-HOOD",
                "material": "Dry Carbon Pre-Preg Composite",
                "weight_kg": 4.9,
                "joint_spec": "M6 Hinge Bolts (16 Nm)",
                "fastener_name": "Dry Carbon Hood Hinge Fastener",
                "fastener_type": "Bolt", "thread_size": "M6x1.0", "drive_type": "Hex 10mm", "grade": "8.8", "torque_spec_nm": 16.0,
                "x_percent": 26.0, "y_percent": 18.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "Front Bumper Fascia with Integrated Brake Cooling Ducts",
                "plainExplainer": "Channels air into high-capacity intercooler and delivers dedicated airflow channels directly into front brake rotors.",
                "part_number": "NIS-R34-AERO-BUMP",
                "material": "Polyurethane & Carbon Front Splitter",
                "weight_kg": 6.8,
                "joint_spec": "Bumper Underbody Retainers (10 Nm)",
                "fastener_name": "Front Splitter Retaining Collar Bolt",
                "fastener_type": "Bolt", "thread_size": "M6x1.0", "drive_type": "Hex 10mm", "grade": "8.8", "torque_spec_nm": 10.0,
                "x_percent": 86.0, "y_percent": 22.0, "qty": 8,
            },
            {
                "category": "Monocoque",
                "name": "Reinforced High-Rigidity Monocoque Chassis & Strut Braces",
                "plainExplainer": "V-Spec II stiffened floor-pan and rear suspension bulkheads engineered to handle massive ATTESA AWD launches.",
                "part_number": "NIS-R34-CHASSIS-BIW",
                "material": "High-Tensile Steel Unibody & Titanium Front Strut Bar",
                "weight_kg": 280.0,
                "joint_spec": "Titanium Strut Bar Nuts (65 Nm)",
                "fastener_name": "Titanium Front Strut Tower Nut",
                "fastener_type": "Nut", "thread_size": "M10x1.25", "drive_type": "Hex 14mm", "grade": "Grade 5 Titanium", "torque_spec_nm": 65.0,
                "x_percent": 50.0, "y_percent": 39.0, "qty": 6,
            },
            {
                "category": "Monocoque",
                "name": "Carbon Fiber Rear Underbody Ground Effect Diffuser",
                "plainExplainer": "Smooth carbon underbody tray creates ground effect venturi suction to suck the rear tires into the tarmac at high speed.",
                "part_number": "NIS-R34-AERO-DIFF",
                "material": "Carbon-Kevlar Composite Panel",
                "weight_kg": 6.2,
                "joint_spec": "Subframe Bracket Fasteners (18 Nm)",
                "fastener_name": "Underbody Venturi Tray Bracket Bolt",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 12mm", "grade": "10.9", "torque_spec_nm": 18.0,
                "x_percent": 68.0, "y_percent": 42.0, "qty": 8,
            },
            {
                "category": "Powertrain",
                "name": "2.6L Twin-Turbocharged Inline-6 Engine (RB26DETT)",
                "plainExplainer": "Legendary cast-iron block with parallel ceramic-wheel twin turbochargers and six individual throttle butterflies.",
                "part_number": "NIS-R34-RB26-ENG",
                "material": "Cast Iron 05U Block & DOHC 24V Aluminum Head",
                "weight_kg": 205.0,
                "joint_spec": "Engine Isolator Mounts (90 Nm)",
                "fastener_name": "RB26 Cast Iron Engine Mount Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 17mm", "grade": "10.9", "torque_spec_nm": 90.0,
                "x_percent": 48.0, "y_percent": 58.0, "qty": 4,
            },
            {
                "category": "Powertrain",
                "name": "Getrag 6-Speed Manual Transmission & ATTESA AWD Transfer",
                "plainExplainer": "Bulletproof 6-speed manual box paired with electronically controlled electro-hydraulic all-wheel drive clutch.",
                "part_number": "NIS-R34-GETRAG-6SPD",
                "material": "Cast Aluminum Housing & High-Nickel Steel Gears",
                "weight_kg": 95.0,
                "joint_spec": "Bellhousing Hardware (55 Nm)",
                "fastener_name": "Getrag Bellhousing to Block Bolt",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Hex 14mm", "grade": "10.9", "torque_spec_nm": 55.0,
                "x_percent": 70.0, "y_percent": 60.0, "qty": 10,
            },
            {
                "category": "Powertrain",
                "name": "Nismo Weldina Titanium Exhaust System",
                "plainExplainer": "Single 80mm titanium pipe with high-flow resonators providing free-flowing exhaust scavenge with a spine-tingling inline-6 tone.",
                "part_number": "NIS-R34-NISMO-EXH",
                "material": "Grade 1 Titanium Sheet & Mandrel Bends",
                "weight_kg": 8.9,
                "joint_spec": "Titanium 2-Bolt Flanges (25 Nm)",
                "fastener_name": "Titanium Exhaust Flange Stud",
                "fastener_type": "Bolt", "thread_size": "M10x1.25", "drive_type": "Hex 14mm", "grade": "Stainless A4", "torque_spec_nm": 25.0,
                "x_percent": 30.0, "y_percent": 67.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "Brembo 4-Piston Gold Monobloc Front Calipers",
                "plainExplainer": "Staggered piston diameters ensure even pad wear and predictable pedal bite on technical racetracks.",
                "part_number": "NIS-R34-BREMBO-GOLD",
                "material": "Forged Monobloc Aluminum (Gold Finish)",
                "weight_kg": 5.1,
                "joint_spec": "Radial Caliper Fasteners (125 Nm)",
                "fastener_name": "Brembo Gold Caliper Mounting Bolt",
                "fastener_type": "Bolt", "thread_size": "M14x1.5", "drive_type": "Hex 19mm", "grade": "12.9", "torque_spec_nm": 125.0,
                "x_percent": 11.5, "y_percent": 75.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "324mm Brembo Slotted Ventilated Front Brake Discs",
                "plainExplainer": "High-carbon heat-treated iron discs with curved directional vanes pumping cooling air through the rotor core.",
                "part_number": "NIS-R34-BREMBO-DISC",
                "material": "High-Carbon Heat-Treated Iron",
                "weight_kg": 9.2,
                "joint_spec": "M12x1.25 Wheel Lug Nuts (110 Nm)",
                "fastener_name": "Rays Forged Wheel Lug Nut",
                "fastener_type": "Nut", "thread_size": "M12x1.25", "drive_type": "Hex 21mm", "grade": "Forged Steel", "torque_spec_nm": 110.0,
                "x_percent": 15.5, "y_percent": 83.0, "qty": 5,
            },
            {
                "category": "Brakes & Gear",
                "name": "Nismo S-Tune Inverted Monotube Coilover Assembly",
                "plainExplainer": "Inverted damper design provides immense lateral stiffness to resist camber deflection under ATTESA AWD cornering.",
                "part_number": "NIS-R34-NISMO-COIL",
                "material": "Inverted Steel Strut Body & Si-Cr Springs",
                "weight_kg": 6.8,
                "joint_spec": "Strut Top Flange Nut (65 Nm)",
                "fastener_name": "Inverted Coilover Upper Mount Nut",
                "fastener_type": "Nut", "thread_size": "M12x1.25", "drive_type": "Hex 17mm", "grade": "10.9", "torque_spec_nm": 65.0,
                "x_percent": 33.0, "y_percent": 79.0, "qty": 6,
            },
            {
                "category": "Hardware",
                "name": "Grade 10.9 Zinc-Coated High-Torque Fastener Grid",
                "plainExplainer": "Ensures critical AWD transfer case and multi-link suspension arms stay torqued under violent AWD launches.",
                "part_number": "NIS-R34-FAST-GRID",
                "material": "Grade 10.9 Zinc-Yellow Steel",
                "weight_kg": 4.2,
                "joint_spec": "M6–M14 Fasteners (12–145 Nm)",
                "fastener_name": "Multi-Link Subframe Yellow Zinc Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.25", "drive_type": "Hex 17mm", "grade": "10.9", "torque_spec_nm": 95.0,
                "x_percent": 74.0, "y_percent": 92.0, "qty": 54,
            },
        ]
        await seed_car_components(skyline_r34, nissan_dossier)

        # =====================================================================
        # 5. VOLKSWAGEN GOLF R (MK8) - 5 TIERS / 12 COMPONENTS
        # =====================================================================
        print("Seeding Volkswagen Golf R (Mk8) knolling component dossiers...")
        vw_dossier = [
            {
                "category": "Aero Shell",
                "name": "R-Performance Dual-Level Roof Spoiler & Winglets",
                "plainExplainer": "Generates high-speed rear axle stability and cleans aerodynamic wake separation over the rear hatch.",
                "part_number": "5H0-827-SPOILER",
                "material": "Blow-Molded ABS & High-Gloss Polyurethane",
                "weight_kg": 3.4,
                "joint_spec": "Torx Fasteners (12 Nm)",
                "fastener_name": "Roof Spoiler Retaining Fastener",
                "fastener_type": "Bolt", "thread_size": "M6x1.0", "drive_type": "Torx T25", "grade": "8.8", "torque_spec_nm": 12.0,
                "x_percent": 74.0, "y_percent": 16.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "Lightweight Aluminum Hood with Acoustic Insulation",
                "plainExplainer": "Shaves front axle weight while maintaining pedestrian crash absorption and acoustic refinement.",
                "part_number": "5H0-823-HOOD",
                "material": "Stamped Aerospace Aluminum Alloy 6016",
                "weight_kg": 6.8,
                "joint_spec": "Hinge Bolts (14 Nm)",
                "fastener_name": "Aluminum Hood Hinge Collar Bolt",
                "fastener_type": "Bolt", "thread_size": "M6x1.0", "drive_type": "Torx T30", "grade": "8.8", "torque_spec_nm": 14.0,
                "x_percent": 26.0, "y_percent": 18.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "Front R Bumper Fascia with Oversized Radiator Intakes",
                "plainExplainer": "Channels ambient air directly to the twin side auxiliary heat exchangers and front brake cooling ducts.",
                "part_number": "5H0-807-BUMPER",
                "material": "Polypropylene Impact Copolymer (PP-EPDM)",
                "weight_kg": 7.1,
                "joint_spec": "Undertray Torx Screws (9 Nm)",
                "fastener_name": "Fascia Lower Underbody Undertray Torx Screw",
                "fastener_type": "Screw", "thread_size": "M6x1.0", "drive_type": "Torx T25", "grade": "8.8", "torque_spec_nm": 9.0,
                "x_percent": 86.0, "y_percent": 22.0, "qty": 12,
            },
            {
                "category": "Monocoque",
                "name": "MQB Evo High-Strength Hot-Stamped Steel Unibody",
                "plainExplainer": "Ultra-high strength hot-formed steel safety cell delivering benchmark torsional stiffness for hatchback dynamics.",
                "part_number": "5WA-500-CHASSIS",
                "material": "Hot-Stamped Boron Steel (22MnB5) & Cold-Rolled Aluminum",
                "weight_kg": 295.0,
                "joint_spec": "Subframe Yield Bolts (70 Nm + 90°)",
                "fastener_name": "MQB Evo Unibody Subframe Stretch Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 70.0,
                "x_percent": 50.0, "y_percent": 39.0, "qty": 8,
            },
            {
                "category": "Monocoque",
                "name": "Front Aluminum Subframe with Solid Bushing Mounts",
                "plainExplainer": "Cast aluminum subframe shaves 3.0 kg over standard Golf while directly mounting steering rack for precise feedback.",
                "part_number": "5WA-199-SUBFRAME",
                "material": "High-Pressure Die-Cast Aluminum",
                "weight_kg": 9.8,
                "joint_spec": "Stretch Bolts (70 Nm + 90°)",
                "fastener_name": "Cast Aluminum Subframe Cross-Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 70.0,
                "x_percent": 68.0, "y_percent": 42.0, "qty": 4,
            },
            {
                "category": "Powertrain",
                "name": "2.0L TSI EA888 Gen 4 Turbocharged Engine",
                "plainExplainer": "Pumps out 320 horsepower and 420 Nm torque with a twin-scroll turbocharger and variable valve lift.",
                "part_number": "06Q-100-EA888",
                "material": "GJL-250 Grey Cast Iron Block & Al-Si Cylinder Head",
                "weight_kg": 142.0,
                "joint_spec": "Hydro-Engine Mount (60 Nm + 90°)",
                "fastener_name": "EA888 Gen 4 Hydro-Bearing Engine Mount Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 60.0,
                "x_percent": 48.0, "y_percent": 58.0, "qty": 2,
            },
            {
                "category": "Powertrain",
                "name": "7-Speed Dual-Clutch DSG Gearbox (DQ381)",
                "plainExplainer": "Pre-selects next gear for seamless power delivery in milliseconds during full-throttle acceleration.",
                "part_number": "0GC-300-DSG",
                "material": "Die-Cast Aluminum Casing & Wet Multi-Plate Clutches",
                "weight_kg": 87.0,
                "joint_spec": "Bellhousing Fasteners (50 Nm)",
                "fastener_name": "DQ381 DSG Bellhousing Mounting Bolt",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Hex 16mm", "grade": "10.9", "torque_spec_nm": 50.0,
                "x_percent": 70.0, "y_percent": 60.0, "qty": 8,
            },
            {
                "category": "Powertrain",
                "name": "R-Performance Torque Vectoring Rear Axle Splitter",
                "plainExplainer": "Uses two independent electro-mechanical clutches to distribute up to 100% of rear drive to the outside wheel in Drift Mode.",
                "part_number": "0CP-525-VECTOR",
                "material": "Die-Cast Aluminum Housing & Multi-Disc Carbon Clutches",
                "weight_kg": 26.5,
                "joint_spec": "Subframe Anchor Bolts (60 Nm + 90°)",
                "fastener_name": "R-Performance Torque Splitter Subframe Anchor",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Hex 16mm", "grade": "10.9", "torque_spec_nm": 60.0,
                "x_percent": 30.0, "y_percent": 67.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "Akebono 2-Piston Floating Front Calipers in R-Blue",
                "plainExplainer": "Stiff caliper carrier bridge ensures firm, progressive pedal response without sponginess.",
                "part_number": "5WA-615-AKEBONO",
                "material": "Cast Aluminum (Gloss Blue Finish with R Logo)",
                "weight_kg": 5.8,
                "joint_spec": "Carrier Bolts (120 Nm)",
                "fastener_name": "Front Caliper Carrier Anchor Bolt",
                "fastener_type": "Bolt", "thread_size": "M14x1.5", "drive_type": "Triple-Square M14", "grade": "10.9", "torque_spec_nm": 120.0,
                "x_percent": 12.0, "y_percent": 76.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "357mm Cross-Drilled 2-Piece Front Brake Rotors",
                "plainExplainer": "Aluminum friction hat design cuts 1.2 kg per corner while cross-drilled holes vent hot gases under track braking.",
                "part_number": "5WA-615-ROTOR",
                "material": "Cast Iron Friction Ring with Steel Pin-Jointed Aluminum Bell",
                "weight_kg": 8.9,
                "joint_spec": "Wheel Lug Bolts (120 Nm)",
                "fastener_name": "Golf R Ball-Seat Lug Bolt",
                "fastener_type": "Bolt", "thread_size": "M14x1.5", "drive_type": "Hex 17mm", "grade": "10.9", "torque_spec_nm": 120.0,
                "x_percent": 16.0, "y_percent": 84.0, "qty": 5,
            },
            {
                "category": "Brakes & Gear",
                "name": "DCC Adaptive Dynamic Chassis Control Damper Struts",
                "plainExplainer": "Electromagnetic valves adjust compression and rebound damping 200 times per second for instant curb compliance.",
                "part_number": "5WA-412-021-DCC",
                "material": "Hard-Chromed Micro-Alloy Steel & Coil Springs",
                "weight_kg": 6.4,
                "joint_spec": "Pinch Bolt (70 Nm + 90°)",
                "fastener_name": "MacPherson Strut Pinch Bolt to Knuckle",
                "fastener_type": "Bolt", "thread_size": "M14x1.5", "drive_type": "Triple-Square M14", "grade": "10.9", "torque_spec_nm": 70.0,
                "x_percent": 33.0, "y_percent": 79.0, "qty": 2,
            },
            {
                "category": "Hardware",
                "name": "Micro-Alloyed Torx T25/T30 & Subframe Stretch Bolt Grid",
                "plainExplainer": "High-grade OEM hardware ensuring zero subframe shifting under violent launch control starts.",
                "part_number": "5WA-007-FAST-GRID",
                "material": "Grade 10.9 Micro-Alloyed Steel",
                "weight_kg": 3.1,
                "joint_spec": "M6–M14 Fasteners (9–140 Nm)",
                "fastener_name": "Dacromet Subframe Stretch Anchor",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 70.0,
                "x_percent": 75.0, "y_percent": 92.0, "qty": 48,
            },
        ]
        await seed_car_components(golf_r, vw_dossier)

        # =====================================================================
        # 6. BMW M4 CSL (G82) - 5 TIERS / 12 COMPONENTS
        # =====================================================================
        print("Seeding BMW M4 CSL knolling component dossiers...")
        bmw_dossier = [
            {
                "category": "Aero Shell",
                "name": "Carbon Fiber Ducktail Trunk Lid & Gurney Lip",
                "plainExplainer": "Eliminates lift over the rear axle with an aerodynamic integrated ducktail paying homage to the legendary 2004 E46 M3 CSL.",
                "part_number": "4162-8083-CSL",
                "material": "CFRP Autoclave Pre-Preg (2x2 Twill)",
                "weight_kg": 3.9,
                "joint_spec": "M6 Torx T30 (10 Nm)",
                "fastener_name": "CSL Trunk Lid Hinge Fastener",
                "fastener_type": "Bolt", "thread_size": "M6x1.0", "drive_type": "Torx T30", "grade": "8.8", "torque_spec_nm": 10.0,
                "x_percent": 78.0, "y_percent": 18.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "CFRP Double-Vented Motorsport Hood",
                "plainExplainer": "Channels air through central cooling vents to vent under-hood turbo temperatures and cut 1.5 kg over the standard M4.",
                "part_number": "4161-8084-CFRP",
                "material": "Visible Carbon Fiber with Clear Lacquer",
                "weight_kg": 5.8,
                "joint_spec": "M8 Hinge Bolts (22 Nm)",
                "fastener_name": "Double-Vented Hood Hinge Pin",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 13mm", "grade": "10.9", "torque_spec_nm": 22.0,
                "x_percent": 24.0, "y_percent": 17.0, "qty": 4,
            },
            {
                "category": "Aero Shell",
                "name": "Full Carbon Fiber Front Splitter & Red Accents",
                "plainExplainer": "Generates direct front axle downforce at high track speeds while directing high-pressure cooling air into the brakes.",
                "part_number": "5111-8085-SPLIT",
                "material": "Autoclaved Carbon Composite",
                "weight_kg": 2.6,
                "joint_spec": "M6 Undertray Fasteners (9 Nm)",
                "fastener_name": "CSL Splitter Undertray Screw",
                "fastener_type": "Screw", "thread_size": "M6x1.0", "drive_type": "Torx T25", "grade": "8.8", "torque_spec_nm": 9.0,
                "x_percent": 84.0, "y_percent": 21.0, "qty": 10,
            },
            {
                "category": "Monocoque",
                "name": "Lightweight Structural Unibody with -100kg Deletion",
                "plainExplainer": "Sheds 100 kilograms by deleting rear seats, reducing sound insulation, and integrating ultra-lightweight acoustic glass.",
                "part_number": "4100-8086-BIW",
                "material": "Multi-Phase High-Strength Steel & Aluminum Subframes",
                "weight_kg": 340.0,
                "joint_spec": "Chassis Subframe Fasteners (75 Nm + 90°)",
                "fastener_name": "Lightweight BIW Subframe Stretch Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 75.0,
                "x_percent": 50.0, "y_percent": 40.0, "qty": 8,
            },
            {
                "category": "Monocoque",
                "name": "Precision Cast Aluminum Front Strut Tower Brace",
                "plainExplainer": "Connects both front spring strut domes to the radiator cowl, neutralizing body twist under high-g lateral cornering.",
                "part_number": "5161-8087-BRACE",
                "material": "High-Vacuum Cast Aluminum Lattice Truss",
                "weight_kg": 3.2,
                "joint_spec": "Torx E14 Strut Dome Bolts (56 Nm + 90°)",
                "fastener_name": "Strut Tower Brace Dome Stretch Bolt",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Torx E14", "grade": "10.9", "torque_spec_nm": 56.0,
                "x_percent": 68.0, "y_percent": 43.0, "qty": 6,
            },
            {
                "category": "Powertrain",
                "name": "3.0L S58 Twin-Turbo Inline-6 Engine (550 PS)",
                "plainExplainer": "Features a 3D-printed cylinder head core, forged lightweight crankshaft, and twin mono-scroll turbos producing 550 hp.",
                "part_number": "1100-8088-S58",
                "material": "Closed-Deck Aluminum Crankcase & Wire-Arc Liners",
                "weight_kg": 194.0,
                "joint_spec": "Hydraulic Engine Mount Bolts (80 Nm)",
                "fastener_name": "S58 Motor Mount to Subframe Bolt",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 80.0,
                "x_percent": 48.0, "y_percent": 58.0, "qty": 4,
            },
            {
                "category": "Powertrain",
                "name": "8-Speed M Steptronic Transmission with Drivelogic",
                "plainExplainer": "Equipped with rigid transmission mounts and calibrated shift kinematics for instant gear engagement on the limit.",
                "part_number": "2400-8089-STEP",
                "material": "Die-Cast Aluminum Housing & Multi-Plate Lockup",
                "weight_kg": 98.0,
                "joint_spec": "Bellhousing Torx Bolts (45 Nm)",
                "fastener_name": "Steptronic Bellhousing Bolt",
                "fastener_type": "Bolt", "thread_size": "M10x1.5", "drive_type": "Torx E12", "grade": "10.9", "torque_spec_nm": 45.0,
                "x_percent": 70.0, "y_percent": 60.0, "qty": 8,
            },
            {
                "category": "Powertrain",
                "name": "Lightweight Titanium Rear Exhaust Silencer",
                "plainExplainer": "Reduces backpressure for faster turbo spool while shedding 4.3 kg off the rear axle with an intoxicating roar.",
                "part_number": "1830-8089-TITAN",
                "material": "Grade 2 Pure Titanium & Electron Beam Welds",
                "weight_kg": 9.2,
                "joint_spec": "M8 V-Band Clamps (24 Nm)",
                "fastener_name": "Titanium Muffler V-Band Clamp",
                "fastener_type": "Bolt", "thread_size": "M8x1.25", "drive_type": "Hex 13mm", "grade": "Inconel 718", "torque_spec_nm": 24.0,
                "x_percent": 29.0, "y_percent": 73.0, "qty": 2,
            },
            {
                "category": "Brakes & Gear",
                "name": "M Carbon Ceramic 6-Piston Front Brake Caliper",
                "plainExplainer": "Squeezes the carbon brake rotor with 6 pistons to stop the car safely under heavy track braking.",
                "part_number": "3411-8090-CC",
                "material": "Monobloc Cast Aluminum (Gloss Red Finish)",
                "weight_kg": 5.2,
                "joint_spec": "Radial Caliper Mounts (140 Nm)",
                "fastener_name": "Radial Mount Caliper Bolt",
                "fastener_type": "Bolt", "thread_size": "M14x1.5", "drive_type": "Hex 19mm", "grade": "12.9", "torque_spec_nm": 140.0,
                "x_percent": 7.0, "y_percent": 74.0, "qty": 4,
            },
            {
                "category": "Brakes & Gear",
                "name": "400mm Carbon Ceramic Ventilated Brake Rotor",
                "plainExplainer": "Dissipates friction temperatures up to 800°C without brake fade while cutting 14 kg of rotating unsprung mass.",
                "part_number": "3411-8091-ROTOR",
                "material": "C/SiC Carbon Ceramic Matrix & Billet Hat",
                "weight_kg": 7.4,
                "joint_spec": "M14x1.25 Lug Bolts (140 Nm)",
                "fastener_name": "CSL Wheel Lug Bolt",
                "fastener_type": "Bolt", "thread_size": "M14x1.25", "drive_type": "Hex 17mm", "grade": "10.9", "torque_spec_nm": 140.0,
                "x_percent": 13.0, "y_percent": 73.0, "qty": 5,
            },
            {
                "category": "Brakes & Gear",
                "name": "CSL Inverted Track Damper & Spring Strut",
                "plainExplainer": "Controls wheel compression over kerbs and bumps to keep tires glued to the racing surface.",
                "part_number": "3131-8092-COIL",
                "material": "Hard-Anodized Aluminum & Si-Cr Spring Steel",
                "weight_kg": 6.8,
                "joint_spec": "Strut Top Nut (64 Nm)",
                "fastener_name": "Inverted Damper Top Mount Nut",
                "fastener_type": "Nut", "thread_size": "M12x1.25", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 64.0,
                "x_percent": 25.5, "y_percent": 41.0, "qty": 2,
            },
            {
                "category": "Hardware",
                "name": "High-Tensile Knolled Fastener & Hardware Grid",
                "plainExplainer": "Precision torqued Grade 10.9 and Grade 5 titanium bolts engineered to withstand track vibrations and sheer forces.",
                "part_number": "0711-8093-FAST",
                "material": "Grade 10.9 Dacromet Steel & Ti-6Al-4V",
                "weight_kg": 3.6,
                "joint_spec": "M6–M14 Fasteners (10–140 Nm)",
                "fastener_name": "Subframe Yield Dacromet Stud",
                "fastener_type": "Bolt", "thread_size": "M12x1.5", "drive_type": "Hex 18mm", "grade": "10.9", "torque_spec_nm": 95.0,
                "x_percent": 36.0, "y_percent": 92.0, "qty": 48,
            },
        ]
        await seed_car_components(bmw_m4, bmw_dossier)

        await session.commit()
        print("Successfully seeded all 5 benchmark motorsport cars + BMW M4 CSL on Neon PostgreSQL with 5-tier knolling component dossiers!")


if __name__ == "__main__":
    asyncio.run(seed_data())
